version: '3.9'

services:
  backend:
    build: .
    container_name: his-backend
    ports:
      - '3000:3000'
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
